# Welcome to Jekyll!
#

# Site settings
title: Kane 4.2
description: We didn't choose the way we're wired, but we can change our software.
owner: Kane McConnell # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: writeme@kanemc.co
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kanemc.co" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/kanemcconnell
  github: https://github.com/kmcconnell
  linkedin-square: https://linkedin.com/in/kanemcconnell
  facebook-official: https://facebook.com/Life-of-Kane-1122307171190900
  google-plus-square: https://plus.google.com/u/0/+KaneMcConnell
  #email: /contact/
  flickr: https://www.flickr.com/photos/kanespix/
  instagram: https://www.instagram.com/kanespix
  youtube-square: https://www.youtube.com/channel/UCzgh6sDmP0QGPhYKdb_N6EQ
  #spotify:
  stack-overflow: http://stackoverflow.com/users/3413346/kane-mcconnell
  vimeo: https://vimeo.com/kanemcconnell
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  tripadvisor: https://www.tripadvisor.com/members/kanemc
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
